### ISSUE TITLE
CSS server has crashed

### ISSUE THREAD

**Issue by SouraTR** [daenuprobst/theia#3]
Chrome devtools returns this. The CSS server is not working.
![image](https://user-images.githubusercontent.com/51744901/236618267-b0b25ab6-7410-48b0-a68f-bbc8b28a6aa2.png)
![image](https://user-images.githubusercontent.com/51744901/236618311-5466ee12-dd6a-4bd4-a5ac-1ced51d083f5.png)
![image](https://user-images.githubusercontent.com/51744901/236618347-fa8ee024-2832-4896-a415-9a3d16cfdb0c.png)

**Comment by daenuprobst** [comment]
Sorry for the late reply. Thank you for bringing it up. I recently fixed this issue.
